sudo: required
services:
  - docker

before_install:
  - docker build -t tommyling79/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tommyling79/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-765793169048"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key: "$AWS_Secret_Key"